
let Test = {
	init(APP) {
		
	}
};


let tmp_entities = {
	"width": 9,
	"entity": [
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 7, "triangle_count": null },
		{ "type": 5, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": 4, "color": null, "orientation": { 	"horizontal": 1, 	"vertical": 0 }, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 5, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 5, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 5, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 5, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 5, "triangle_count": null },
		{ "type": 7, "color": 2, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": 7, "color": 2, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 13, "triangle_count": null },
		{ "type": 7, "color": 1, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": 7, "color": 1, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 2, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 2, "triangle_count": null },
		{ "type": 5, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": 5, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 10, "triangle_count": null },
		{ "type": 7, "color": 1, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 8, "triangle_count": null },
		{ "type": 5, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 6, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 6, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 6, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 6, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 6, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 6, "triangle_count": null },
		{ "type": 7, "color": 2, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": 7, "color": 1, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": 7, "color": 2, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 3, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 3, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 3, "triangle_count": null },
		{ "type": 3, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 4, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 4, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 4, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 4, "triangle_count": null },
		{ "type": 5, "color": null, "orientation": null, "shape": null, "count": null, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 3, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 3, "triangle_count": null },
		{ "type": null, "color": null, "orientation": null, "shape": null, "count": 3, "triangle_count": null }
	],
	"symmetry": null
};

